#!/bin/sh

. mount_emmc

BKUP_DIR=${EMMC_ROOT}/opt/Embitude

if [ ! -f ${BKUP_DIR}/MLO ] || [ ! -f ${BKUP_DIR}/u-boot.img ]
then
	. umount_emmc
	echo "No backup to restore. Run 'backup_bl' to take a backup first."
	exit 1
fi

if (mountpoint -q ${EMMC_BOOT}) # Old BBB Rev C
then
	cd ${EMMC_BOOT}
	rm -f MLO u-boot.img
	cd - > /dev/null
else
	eMMC=/dev/$(ls /sys/bus/mmc/devices/mmc1*/block)

	dd if=/dev/zero of=${eMMC} bs=512 seek=1 count=2047 conv=notrunc 2> /dev/null
fi
sync

. umount_emmc

if [ "$1" != "-q" ]
then
	echo "Erasing bootloader(s) successful."
	echo
	echo "*** Now, do a 'poweroff'. Then, remove the uSD (if inserted) and do a cold reboot. ***"
	echo
fi
